### ISSUE TITLE
Warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by vhiairrassary** [0ctobat/octobat-ruby#7]
We are using this gem with Ruby 2.7 and we our logs are full of the following warning:
```
.../.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/octobat-2.0.25/lib/octobat/util.rb:127: warning: URI.escape is obsolete
```

Would it be possible to fix it please?

**Comment by ksol** [comment]
Same issue here, @0ctobat. I'm willing to take the time to open a PR if you're open to external contributions

**Comment by zuuno** [comment]
Hi guys,

PR are accepted, so, don't hesitate to open one, and I will look at it :-).
Thanks a lot,

**Comment by vhiairrassary** [comment]
On my side, as there is not yet unit test, I don't feel enough confident to create the PR (I am not sure about what could be impacted outside direct callees).

It seems there is no official replacement, but hopefully something like https://stackoverflow.com/a/67618304/1376828 is ok.

**Comment by ksol** [comment]
We opened #8 in hopes that it solves the issue (or gets the ball rolling). Let us know if anything else is needed !

**Comment by vhiairrassary** [comment]
Thank for the PR. This is blocking on our side as `URI.escape` has been removed from Ruby 3

**Comment by 0ctobat** [comment]
PR accepted! Thanks a lot!
